# docker-compose.prod.yml (Production)
services:
  # Nginx + Frontend Static Files
  nginx:
    image: ghcr.io/arif14377/koda-b6-frontend:${FRONTEND_IMAGE_TAG:-latest}
    container_name: web-arif
    restart: always
    ports:
      - "20101:80"
    depends_on:
      - backend
    networks:
      - pman_web

  # Backend (Node.js — menggantikan backend-go)
  backend:
    image: ghcr.io/arif14377/koda-b6-backend-node:${BACKEND_NODE_IMAGE_TAG:-latest}
    container_name: backend-arif-nodejs
    restart: always
    ports:
      - "20105:8888"
    environment:
      - PORT=8888
      - PGHOST=pg
      - PGPORT=5432
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGSSLMODE=disable
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://:${REDIS_SECRET}@redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SECRET=${REDIS_SECRET}
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pman_web
      - server-arif_webapps

  # Database / Postgres
  pg:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pman_web
      - server-arif_webapps

  # Redis
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_SECRET}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_SECRET}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pman_web
      - server-arif_webapps

  # Migration
  migrate:
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${PGUSER}:${PGPASSWORD}@pg:5432/${PGDATABASE}?sslmode=disable
      - up
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - pman_web

networks:
  pman_web:
    external: true
  server-arif_webapps:
    external: true
